spring:
  application:
    name: SchoolAPI
  datasource:
      url: jdbc:postgresql://localhost:5431/school # for local development
      #url: jdbc:postgresql://schooldb:5432/school for docker
      username: admin
      password: 1234
      driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  server:
    servlet:
      session:
        timeout: 20m
        