import type { ResourceDefinition } from "@/lib/types";

export const resourceCatalog: ResourceDefinition[] = [
  {
    slug: "auth",
    title: "Autenticacao",
    description: "Valida o Bearer token atual e retorna as claims resolvidas pela API.",
    allowedRoles: ["ROLE_ADMIN", "ROLE_TEACHER"],
    actions: [
      {
        id: "auth-me",
        label: "Ver usuario autenticado",
        method: "GET",
        pathTemplate: "/auth/me",
        description: "Consulta o endpoint protegido que devolve o JWT parseado pelo backend.",
      },
    ],
  },
  {
    slug: "departments",
    title: "Departamentos",
    description: "CRUD de departamentos e consulta de professores vinculados.",
    allowedRoles: ["ROLE_ADMIN", "ROLE_TEACHER"],
    actions: [
      {
        id: "departments-list",
        label: "Listar departamentos",
        method: "GET",
        pathTemplate: "/departments",
        description: "Carrega todos os departamentos.",
      },
      {
        id: "departments-create",
        label: "Criar departamento",
        method: "POST",
        pathTemplate: "/departments",
        description: "Cria um novo departamento pelo DTO principal.",
        sampleBody: {
          name: "Matematica",
        },
      },
      {
        id: "departments-by-id",
        label: "Buscar por ID",
        method: "GET",
        pathTemplate: "/departments/{id}",
        description: "Consulta um departamento específico.",
        pathParams: [{ name: "id", label: "ID do departamento", placeholder: "1" }],
      },
      {
        id: "departments-by-name",
        label: "Buscar por nome",
        method: "GET",
        pathTemplate: "/departments/name",
        description: "Usa query string para localizar um departamento pelo nome.",
        queryParams: [{ name: "name", label: "Nome", placeholder: "Matematica" }],
      },
      {
        id: "departments-teachers",
        label: "Buscar professores do departamento",
        method: "GET",
        pathTemplate: "/departments/{id}/teachers",
        description: "Retorna o departamento com a lista de professores carregada.",
        pathParams: [{ name: "id", label: "ID do departamento", placeholder: "1" }],
      },
      {
        id: "departments-update",
        label: "Atualizar departamento",
        method: "PUT",
        pathTemplate: "/departments/{id}",
        description: "Atualiza apenas o nome do departamento.",
        pathParams: [{ name: "id", label: "ID do departamento", placeholder: "1" }],
        sampleBody: {
          name: "Matematica Aplicada",
        },
      },
      {
        id: "departments-delete",
        label: "Excluir departamento",
        method: "DELETE",
        pathTemplate: "/departments/{id}",
        description: "Remove o departamento e retorna 204 quando funciona.",
        pathParams: [{ name: "id", label: "ID do departamento", placeholder: "1" }],
      },
    ],
  },
  {
    slug: "subjects",
    title: "Materias",
    description: "Cadastro das disciplinas e buscas por nome.",
    allowedRoles: ["ROLE_ADMIN", "ROLE_TEACHER"],
    actions: [
      {
        id: "subjects-list",
        label: "Listar materias",
        method: "GET",
        pathTemplate: "/subjects",
        description: "Carrega as disciplinas cadastradas.",
      },
      {
        id: "subjects-create",
        label: "Criar materia",
        method: "POST",
        pathTemplate: "/subjects",
        description: "Cria uma disciplina simples pelo SubjectDto.",
        sampleBody: {
          name: "Algebra Linear",
        },
      },
      {
        id: "subjects-by-id",
        label: "Buscar por ID",
        method: "GET",
        pathTemplate: "/subjects/{id}",
        description: "Retorna o DTO resumido da disciplina.",
        pathParams: [{ name: "id", label: "ID da materia", placeholder: "1" }],
      },
      {
        id: "subjects-by-name",
        label: "Buscar por nome com professores",
        method: "GET",
        pathTemplate: "/subjects/name/{name}",
        description: "Consulta a disciplina com o relacionamento de professores carregado.",
        pathParams: [{ name: "name", label: "Nome da materia", placeholder: "Algebra Linear" }],
      },
      {
        id: "subjects-by-name-simple",
        label: "Buscar por nome simples",
        method: "GET",
        pathTemplate: "/subjects/nameSubject/{name}",
        description: "Consulta a disciplina sem a rota especializada de professores.",
        pathParams: [{ name: "name", label: "Nome da materia", placeholder: "Algebra Linear" }],
      },
      {
        id: "subjects-update",
        label: "Atualizar materia",
        method: "PUT",
        pathTemplate: "/subjects/{id}",
        description: "Atualiza apenas o nome da disciplina.",
        pathParams: [{ name: "id", label: "ID da materia", placeholder: "1" }],
        sampleBody: {
          name: "Calculo I",
        },
      },
      {
        id: "subjects-delete",
        label: "Excluir materia",
        method: "DELETE",
        pathTemplate: "/subjects/{id}",
        description: "Remove a disciplina.",
        pathParams: [{ name: "id", label: "ID da materia", placeholder: "1" }],
      },
    ],
  },
  {
    slug: "teachers",
    title: "Professores",
    description: "CRUD dos professores e consultas de subjects/departments relacionados.",
    allowedRoles: ["ROLE_ADMIN"],
    actions: [
      {
        id: "teachers-list",
        label: "Listar professores",
        method: "GET",
        pathTemplate: "/teachers",
        description: "Carrega todos os professores.",
      },
      {
        id: "teachers-create",
        label: "Criar professor",
        method: "POST",
        pathTemplate: "/teachers",
        description: "Cria um professor vinculando disciplinas pelo nome.",
        sampleBody: {
          name: "Maria Souza",
          email: "maria@school.local",
          subject: ["Algebra Linear"],
        },
      },
      {
        id: "teachers-by-id",
        label: "Buscar por ID",
        method: "GET",
        pathTemplate: "/teachers/{id}",
        description: "Busca o TeacherDto com os nomes das disciplinas.",
        pathParams: [{ name: "id", label: "ID do professor", placeholder: "1" }],
      },
      {
        id: "teachers-subjects",
        label: "Buscar materias do professor",
        method: "GET",
        pathTemplate: "/teachers/{id}/subjects",
        description: "Retorna apenas os nomes das disciplinas do professor.",
        pathParams: [{ name: "id", label: "ID do professor", placeholder: "1" }],
      },
      {
        id: "teachers-department",
        label: "Buscar departamento do professor",
        method: "GET",
        pathTemplate: "/teachers/{id}/department",
        description: "Retorna o nome do departamento atual do professor.",
        pathParams: [{ name: "id", label: "ID do professor", placeholder: "1" }],
      },
      {
        id: "teachers-by-department",
        label: "Buscar por nome do departamento",
        method: "GET",
        pathTemplate: "/teachers/department/{name}",
        description: "Lista professores pelo nome do departamento.",
        pathParams: [{ name: "name", label: "Nome do departamento", placeholder: "Matematica" }],
      },
      {
        id: "teachers-update",
        label: "Atualizar professor",
        method: "PUT",
        pathTemplate: "/teachers/{id}",
        description: "Atualiza nome e email do professor.",
        pathParams: [{ name: "id", label: "ID do professor", placeholder: "1" }],
        sampleBody: {
          name: "Maria Souza Lima",
          email: "maria.souza@school.local",
        },
      },
      {
        id: "teachers-delete",
        label: "Excluir professor",
        method: "DELETE",
        pathTemplate: "/teachers/{id}",
        description: "Remove o professor do sistema.",
        pathParams: [{ name: "id", label: "ID do professor", placeholder: "1" }],
      },
    ],
  },
  {
    slug: "school-classes",
    title: "Turmas",
    description: "Cadastro das turmas e visualização dos estudantes associados.",
    allowedRoles: ["ROLE_ADMIN", "ROLE_TEACHER"],
    actions: [
      {
        id: "classes-list",
        label: "Listar turmas",
        method: "GET",
        pathTemplate: "/school-classes",
        description: "Carrega todas as turmas.",
      },
      {
        id: "classes-create",
        label: "Criar turma",
        method: "POST",
        pathTemplate: "/school-classes",
        description: "Cria uma turma pelo código.",
        sampleBody: {
          classCode: "A1",
        },
      },
      {
        id: "classes-by-id",
        label: "Buscar por ID",
        method: "GET",
        pathTemplate: "/school-classes/{id}",
        description: "Retorna o SchoolClassDto resumido.",
        pathParams: [{ name: "id", label: "ID da turma", placeholder: "1" }],
      },
      {
        id: "classes-by-code",
        label: "Buscar por codigo",
        method: "GET",
        pathTemplate: "/school-classes/code/{classCode}",
        description: "Busca a turma pelo classCode.",
        pathParams: [{ name: "classCode", label: "Codigo da turma", placeholder: "A1" }],
      },
      {
        id: "classes-students",
        label: "Buscar alunos da turma",
        method: "GET",
        pathTemplate: "/school-classes/code/{classCode}/students",
        description: "Retorna a turma com a lista de estudantes populada.",
        pathParams: [{ name: "classCode", label: "Codigo da turma", placeholder: "A1" }],
      },
      {
        id: "classes-update",
        label: "Atualizar turma",
        method: "PUT",
        pathTemplate: "/school-classes/{id}",
        description: "Atualiza o classCode da turma.",
        pathParams: [{ name: "id", label: "ID da turma", placeholder: "1" }],
        sampleBody: {
          classCode: "B2",
        },
      },
      {
        id: "classes-delete",
        label: "Excluir turma",
        method: "DELETE",
        pathTemplate: "/school-classes/{id}",
        description: "Remove a turma e devolve 204 quando funcionar.",
        pathParams: [{ name: "id", label: "ID da turma", placeholder: "1" }],
      },
    ],
  },
  {
    slug: "students",
    title: "Estudantes",
    description: "Cadastro de alunos e consultas por matrícula.",
    allowedRoles: ["ROLE_ADMIN", "ROLE_TEACHER"],
    actions: [
      {
        id: "students-list",
        label: "Listar estudantes",
        method: "GET",
        pathTemplate: "/students",
        description: "Carrega todos os estudantes.",
      },
      {
        id: "students-create",
        label: "Criar estudante",
        method: "POST",
        pathTemplate: "/students",
        description: "Cria um estudante vinculando a turma pelo classCode.",
        sampleBody: {
          name: "Joao Silva",
          registration: "2026-001",
          schoolClassCode: "A1",
        },
      },
      {
        id: "students-by-id",
        label: "Buscar por ID",
        method: "GET",
        pathTemplate: "/students/{id}",
        description: "Retorna o StudentDto resumido.",
        pathParams: [{ name: "id", label: "ID do estudante", placeholder: "1" }],
      },
      {
        id: "students-by-registration",
        label: "Buscar por matricula",
        method: "GET",
        pathTemplate: "/students/registration/{registration}",
        description: "Consulta o estudante usando a matrícula.",
        pathParams: [{ name: "registration", label: "Matricula", placeholder: "2026-001" }],
      },
      {
        id: "students-update",
        label: "Atualizar estudante",
        method: "PUT",
        pathTemplate: "/students/{id}",
        description: "Atualiza nome e matrícula do estudante.",
        pathParams: [{ name: "id", label: "ID do estudante", placeholder: "1" }],
        sampleBody: {
          name: "Joao da Silva",
          registration: "2026-001",
        },
      },
      {
        id: "students-delete",
        label: "Excluir estudante",
        method: "DELETE",
        pathTemplate: "/students/{id}",
        description: "Remove o estudante selecionado.",
        pathParams: [{ name: "id", label: "ID do estudante", placeholder: "1" }],
      },
    ],
  },
  {
    slug: "gpa",
    title: "Notas",
    description: "Lançamento de notas, médias finais e consultas por aluno.",
    allowedRoles: ["ROLE_TEACHER"],
    actions: [
      {
        id: "gpa-list",
        label: "Listar lancamentos",
        method: "GET",
        pathTemplate: "/gpa",
        description: "Carrega todos os registros de nota.",
      },
      {
        id: "gpa-create",
        label: "Criar lancamento",
        method: "POST",
        pathTemplate: "/gpa",
        description: "Cria uma nota completa usando Student e Subject aninhados.",
        sampleBody: {
          g1: 20,
          g2: 25,
          g3: 35,
          finalGrade: 80,
          subject: { id: 1 },
          student: { id: 1 },
          status: "APPROVED",
        },
      },
      {
        id: "gpa-by-id",
        label: "Buscar por ID",
        method: "GET",
        pathTemplate: "/gpa/{id}",
        description: "Retorna o GPADto pelo identificador.",
        pathParams: [{ name: "id", label: "ID da nota", placeholder: "1" }],
      },
      {
        id: "gpa-by-student",
        label: "Buscar por estudante",
        method: "GET",
        pathTemplate: "/gpa/student/{studentId}",
        description: "Lista todas as notas de um estudante.",
        pathParams: [{ name: "studentId", label: "ID do estudante", placeholder: "1" }],
      },
      {
        id: "gpa-final-grade",
        label: "Buscar nota final por materia",
        method: "GET",
        pathTemplate: "/gpa/student/{studentId}/subject/{subjectId}/final-grade",
        description: "Consulta apenas a nota final entre aluno e matéria.",
        pathParams: [
          { name: "studentId", label: "ID do estudante", placeholder: "1" },
          { name: "subjectId", label: "ID da materia", placeholder: "1" },
        ],
      },
      {
        id: "gpa-final-grades",
        label: "Listar notas finais do estudante",
        method: "GET",
        pathTemplate: "/gpa/student/{studentId}/final-grades",
        description: "Lista as notas finais do estudante.",
        pathParams: [{ name: "studentId", label: "ID do estudante", placeholder: "1" }],
      },
      {
        id: "gpa-update",
        label: "Atualizar lancamento",
        method: "PUT",
        pathTemplate: "/gpa/{id}",
        description: "Atualiza o lançamento e deixa a média ser recalculada no backend.",
        pathParams: [{ name: "id", label: "ID da nota", placeholder: "1" }],
        sampleBody: {
          g1: 18,
          g2: 26,
          g3: 34,
          finalGrade: 78,
          subject: { id: 1 },
          student: { id: 1 },
          status: "IN_PROGRESS",
        },
      },
      {
        id: "gpa-delete",
        label: "Excluir lancamento",
        method: "DELETE",
        pathTemplate: "/gpa/{id}",
        description: "Remove um lançamento específico.",
        pathParams: [{ name: "id", label: "ID da nota", placeholder: "1" }],
      },
    ],
  },
  {
    slug: "users",
    title: "Usuarios locais",
    description: "CRUD administrativo dos usuários persistidos no banco da API.",
    allowedRoles: ["ROLE_ADMIN"],
    actions: [
      {
        id: "users-list",
        label: "Listar usuarios",
        method: "GET",
        pathTemplate: "/users",
        description: "Lista os usuários locais com id, username e roles.",
      },
      {
        id: "users-create",
        label: "Criar usuario",
        method: "POST",
        pathTemplate: "/users",
        description: "Cria um usuário local da API.",
        sampleBody: {
          username: "operador",
          password: "Senha123!",
          role: "admin",
        },
      },
      {
        id: "users-by-username",
        label: "Buscar por username",
        method: "GET",
        pathTemplate: "/users/{username}",
        description: "Busca um usuário local pelo username.",
        pathParams: [{ name: "username", label: "Username", placeholder: "operador" }],
      },
      {
        id: "users-update",
        label: "Atualizar usuario",
        method: "PUT",
        pathTemplate: "/users/{username}",
        description: "Atualiza username, senha e role do usuário local.",
        pathParams: [{ name: "username", label: "Username atual", placeholder: "operador" }],
        sampleBody: {
          username: "operador",
          password: "Senha123!",
          role: "teacher",
        },
      },
      {
        id: "users-delete",
        label: "Excluir usuario",
        method: "DELETE",
        pathTemplate: "/users/{username}",
        description: "Remove o usuário local selecionado.",
        pathParams: [{ name: "username", label: "Username", placeholder: "operador" }],
      },
    ],
  },
];

export function getResourceBySlug(slug: string) {
  return resourceCatalog.find((resource) => resource.slug === slug);
}
